console.log("Torta invertida de manzana");
console.log("Ingredientes:");
console.log("1/4 taza de aceite, 2 tazas de azúcar, 2 huevos, 2 tazas de leche, 3 tazas de harina, 2 manzanas, vainilla");
console.log("Unir el aceite y 1 taza de azúcar");
console.log("Agregar los huevos y batir. Agregar un chorrito de escencia de vainilla");
console.log("Incorporar de a poco harina y leche e ir batiendo hasta unir todo");
console.log("Poner en el molde una taza de azúcar y hacer el caramelo");
console.log("Colocar las manzanas, /(ya cortadas en rodajas)/ sobre el caramelo");
console.log("Volcar la preparación de la torta");
console.log("Dejar cocinar a fuego bajo durante 1hs 30´");
